/** Logical texture keys → files. Swap art later by replacing files or editing this map. */
export const IMAGES: Record<string, string> = {
  'player-idle': 'assets/player/idle.png',
  'player-walk1': 'assets/player/walk1.png',
  'player-walk2': 'assets/player/walk2.png',
  'player-jump': 'assets/player/jump.png',
  'player-hurt': 'assets/player/hurt.png',
  'player-duck': 'assets/player/duck.png',
  'player-front': 'assets/player/front.png',

  'enemy-walker': 'assets/enemy/walker.png',
  'enemy-walker-move': 'assets/enemy/walker-move.png',
  'enemy-walker-hit': 'assets/enemy/walker-hit.png',
  'enemy-walker-dead': 'assets/enemy/walker-dead.png',
  'enemy-flyer': 'assets/enemy/flyer.png',
  'enemy-flyer-move': 'assets/enemy/flyer-move.png',
  'enemy-flyer-dead': 'assets/enemy/flyer-dead.png',
  'enemy-shell': 'assets/enemy/shell.png',
  'enemy-shell-move': 'assets/enemy/shell-move.png',
  'enemy-boss': 'assets/enemy/boss.png',
  'enemy-boss-move': 'assets/enemy/boss-move.png',
  'enemy-boss-dead': 'assets/enemy/boss-dead.png',

  'tile-stone': 'assets/tiles/stone.png',
  'tile-stone-mid': 'assets/tiles/stone-mid.png',
  'tile-stone-left': 'assets/tiles/stone-left.png',
  'tile-stone-right': 'assets/tiles/stone-right.png',
  'tile-stone-center': 'assets/tiles/stone-center.png',
  'tile-stone-half': 'assets/tiles/stone-half.png',
  'tile-stone-half-mid': 'assets/tiles/stone-half-mid.png',
  'tile-stone-half-left': 'assets/tiles/stone-half-left.png',
  'tile-stone-half-right': 'assets/tiles/stone-half-right.png',
  'tile-brick': 'assets/tiles/brick.png',
  'tile-brick-brown': 'assets/tiles/brick-brown.png',

  'prop-door-mid': 'assets/props/door-mid.png',
  'prop-door-top': 'assets/props/door-top.png',
  'prop-torch1': 'assets/props/torch1.png',
  'prop-torch2': 'assets/props/torch2.png',
  'prop-shrine': 'assets/props/shrine.png',
  'prop-bush': 'assets/props/bush.png',
  'prop-rock': 'assets/props/rock.png',
  'prop-window': 'assets/props/window.png',
  'prop-sign-exit': 'assets/props/sign-exit.png',
  'prop-crate': 'assets/props/crate.png',
  'prop-fence': 'assets/props/fence.png',
  'prop-flag': 'assets/props/flag.png',

  'hazard-spikes': 'assets/hazard/spikes.png',
  'hazard-saw': 'assets/hazard/saw.png',
  'hazard-saw-move': 'assets/hazard/saw-move.png',

  'pickup-hp': 'assets/pickups/hp.png',
  'pickup-mp': 'assets/pickups/mp.png',
  'pickup-coin': 'assets/pickups/coin.png',
  'fx-star': 'assets/fx/star.png',

  'hud-heart-full': 'assets/hud/heart-full.png',
  'hud-heart-empty': 'assets/hud/heart-empty.png',
  'hud-heart-half': 'assets/hud/heart-half.png',
  'hud-mp-full': 'assets/hud/mp-full.png',
  'hud-mp-empty': 'assets/hud/mp-empty.png',

  'bg-far': 'assets/bg/far.png',
  'bg-title': 'assets/bg/title.png'
};
